apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Flextrack-microservices-helm-chart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: apps
    repoURL: 'https://github.com/cloudhein/Charts.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true